version: '3'
services:
  python:
    build:
      context: ./
      dockerfile: ./docker/python.dockerfile
      args:
        - userid=${UID}
    command: python -u -m http.server
    volumes:
      - ./webroot:/app
    ports:
      - "8000:8000"
  webpack:
    build:
      context: ./
      dockerfile: ./docker/webpack.dockerfile
      args:
        - userid=${UID}
    command: npm run watch
    volumes:
      - ./webpack.dev.js:/app/webpack.dev.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./webroot/.build:/app/build
      - ./src:/app/src
