version: '3'
services:
  python:
    build:
      context: ./
      dockerfile: ./docker/python.dockerfile
      args:
        - userid=${UID}
    command: python -u -m http.server
    working_dir: /home/python
    volumes:
      - .:/home/python
    ports:
      - "8000:8000"
  webpack:
    build:
      context: ./
      dockerfile: ./docker/webpack.dockerfile
      args:
        - userid=${UID}
    command: npm run watch
    working_dir: /home/webpack
    volumes:
      - ./webpack.dev.js:/home/webpack/webpack.dev.js
      - ./tsconfig.json:/home/webpack/tsconfig.json
      - ./package.json:/home/webpack/package.json
      - ./package-lock.json:/home/webpack/package-lock.json
      - ./build:/home/webpack/build
      - ./src:/home/webpack/src
